export interface Relationship {
  personA: string,
  personB: string,
  weight: number
}

export const RELATIONSHIPS: Relationship[] = [
  {personA: 'SJJ', personB: 'PZ', weight: 3},
  {personA: 'SJJ', personB: 'BH', weight: 2},
  {personA: 'SJJ', personB: 'TEK', weight: 2},
  {personA: 'SJJ', personB: 'BA', weight: 3},
  {personA: 'SJJ', personB: 'HAA', weight: 2},
  {personA: 'SJJ', personB: 'AVB', weight: 1},
  {personA: 'SJJ', personB: 'CLR', weight: 2},
  {personA: 'SJJ', personB: 'YTP', weight: 3},
  {personA: 'SJJ', personB: 'LFC', weight: 3},
  {personA: 'SJJ', personB: 'NPC', weight: 2},
  {personA: 'SJJ', personB: 'HDA', weight: 1},
  {personA: 'SJJ', personB: 'HAD', weight: 1},
  {personA: 'SJJ', personB: 'RW', weight: 1},
  {personA: 'LFC', personB: 'PZ', weight: 2},
  {personA: 'LFC', personB: 'TEK', weight: 2},
  {personA: 'LFC', personB: 'HCY', weight: 2},
  {personA: 'LFC', personB: 'CML', weight: 2},
  {personA: 'LFC', personB: 'LDE', weight: 2},
  {personA: 'LFC', personB: 'PMF', weight: 2},
  {personA: 'LFC', personB: 'CCY', weight: 1},
  {personA: 'LFC', personB: 'CHA', weight: 1},
  {personA: 'LFC', personB: 'MKL', weight: 1},
  {personA: 'LFC', personB: 'YTP', weight: 3},
  {personA: 'LFC', personB: 'NPC', weight: 3},
  {personA: 'LFC', personB: 'FC', weight: 1},
  {personA: 'NPC', personB: 'PZ', weight: 1},
  {personA: 'NPC', personB: 'BA', weight: 3},
  {personA: 'NPC', personB: 'LDE', weight: 1},
  {personA: 'NPC', personB: 'CJE', weight: 3},
  {personA: 'NPC', personB: 'CCY', weight: 2},
  {personA: 'NPC', personB: 'FEL', weight: 2},
  {personA: 'NPC', personB: 'BHW', weight: 2},
  {personA: 'NPC', personB: 'HAA', weight: 1},
  {personA: 'NPC', personB: 'WJH', weight: 1},
  {personA: 'NPC', personB: 'YTP', weight: 2},
  {personA: 'NPC', personB: 'HDA', weight: 3},
  {personA: 'NPC', personB: 'LKW', weight: 2},
  {personA: 'NPC', personB: 'TKH', weight: 1},
  {personA: 'NPC', personB: 'TYS', weight: 1},
  {personA: 'HDA', personB: 'PZ', weight: 3},
  {personA: 'HDA', personB: 'BH', weight: 1},
  {personA: 'HDA', personB: 'TEK', weight: 3},
  {personA: 'HDA', personB: 'HCY', weight: 1},
  {personA: 'HDA', personB: 'CML', weight: 1},
  {personA: 'HDA', personB: 'LDE', weight: 1},
  {personA: 'HDA', personB: 'YML', weight: 3},
  {personA: 'HDA', personB: 'HEL', weight: 3},
  {personA: 'HDA', personB: 'CLR', weight: 3},
  {personA: 'HDA', personB: 'CCW', weight: 2},
  {personA: 'HDA', personB: 'SWY', weight: 1},
  {personA: 'HDA', personB: 'HAD', weight: 2},
  {personA: 'HDA', personB: 'RW', weight: 1},
  {personA: 'HAD', personB: 'PZ', weight: 2},
  {personA: 'HAD', personB: 'BH', weight: 3},
  {personA: 'HAD', personB: 'PMF', weight: 3},
  {personA: 'HAD', personB: 'HEL', weight: 1},
  {personA: 'HAD', personB: 'FEL', weight: 3},
  {personA: 'HAD', personB: 'CLR', weight: 2},
  {personA: 'HAD', personB: 'CHA', weight: 2},
  {personA: 'HAD', personB: 'RW', weight: 1},
  {personA: 'HAD', personB: 'FC', weight: 2},
  {personA: 'HAD', personB: 'WDJ', weight: 2},
  {personA: 'YPF', personB: 'PZ', weight: 3},
  {personA: 'YPF', personB: 'BH', weight: 2},
  {personA: 'YPF', personB: 'TEK', weight: 2},
  {personA: 'YPF', personB: 'HCY', weight: 2},
  {personA: 'YPF', personB: 'LDE', weight: 3},
  {personA: 'YPF', personB: 'HEL', weight: 1},
  {personA: 'YPF', personB: 'BHW', weight: 1},
  {personA: 'YPF', personB: 'HAA', weight: 1},
  {personA: 'YPF', personB: 'MMR', weight: 1},
  {personA: 'YPF', personB: 'AVB', weight: 1},
  {personA: 'YPF', personB: 'CAS', weight: 1},
  {personA: 'YPF', personB: 'WDJ', weight: 1},
  {personA: 'SCS', personB: 'PZ', weight: 1},
  {personA: 'SCS', personB: 'BH', weight: 2},
  {personA: 'SCS', personB: 'TEK', weight: 1},
  {personA: 'SCS', personB: 'BA', weight: 1},
  {personA: 'SCS', personB: 'HCY', weight: 2},
  {personA: 'SCS', personB: 'CJE', weight: 2},
  {personA: 'SCS', personB: 'PMF', weight: 3},
  {personA: 'SCS', personB: 'HEL', weight: 2},
  {personA: 'SCS', personB: 'BHW', weight: 3},
  {personA: 'SCS', personB: 'MHT', weight: 2},
  {personA: 'SCS', personB: 'TKH', weight: 3},
  {personA: 'SCS', personB: 'YTP', weight: 1},
  {personA: 'LKW', personB: 'PZ', weight: 1},
  {personA: 'LKW', personB: 'HCY', weight: 3},
  {personA: 'LKW', personB: 'CJE', weight: 1},
  {personA: 'LKW', personB: 'HEL', weight: 1},
  {personA: 'LKW', personB: 'MMR', weight: 2},
  {personA: 'LKW', personB: 'WJH', weight: 1},
  {personA: 'LKW', personB: 'MHT', weight: 1},
  {personA: 'LKW', personB: 'TYS', weight: 3},
  {personA: 'LKW', personB: 'TKH', weight: 3},
  {personA: 'LKW', personB: 'FC', weight: 2},
  {personA: 'LKW', personB: 'MKL', weight: 1},
  {personA: 'FC', personB: 'PZ', weight: 2},
  {personA: 'FC', personB: 'BH', weight: 3},
  {personA: 'FC', personB: 'TEK', weight: 1},
  {personA: 'FC', personB: 'HCY', weight: 3},
  {personA: 'FC', personB: 'CML', weight: 1},
  {personA: 'FC', personB: 'YML', weight: 1},
  {personA: 'FC', personB: 'WEC', weight: 3},
  {personA: 'FC', personB: 'FEL', weight: 2},
  {personA: 'FC', personB: 'BHW', weight: 1},
  {personA: 'FC', personB: 'CLR', weight: 1},
  {personA: 'FC', personB: 'CHA', weight: 3},
  {personA: 'FC', personB: 'SWY', weight: 3},
  {personA: 'FC', personB: 'WDJ', weight: 2},
  {personA: 'FC', personB: 'GR', weight: 1},
  {personA: 'SWY', personB: 'PZ', weight: 1},
  {personA: 'SWY', personB: 'TEK', weight: 1},
  {personA: 'SWY', personB: 'HCY', weight: 2},
  {personA: 'SWY', personB: 'CML', weight: 3},
  {personA: 'SWY', personB: 'LDE', weight: 1},
  {personA: 'SWY', personB: 'HEL', weight: 1},
  {personA: 'SWY', personB: 'FEL', weight: 1},
  {personA: 'SWY', personB: 'CAS', weight: 1},
  {personA: 'SWY', personB: 'YCH', weight: 1},
  {personA: 'CAS', personB: 'PZ', weight: 3},
  {personA: 'CAS', personB: 'TEK', weight: 1},
  {personA: 'CAS', personB: 'HCY', weight: 1},
  {personA: 'CAS', personB: 'CML', weight: 3},
  {personA: 'CAS', personB: 'CCY', weight: 3},
  {personA: 'CAS', personB: 'FEL', weight: 3},
  {personA: 'CAS', personB: 'WDJ', weight: 1},
  {personA: 'WDJ', personB: 'BH', weight: 2},
  {personA: 'WDJ', personB: 'TEK', weight: 3},
  {personA: 'WDJ', personB: 'CJE', weight: 1},
  {personA: 'WDJ', personB: 'CCY', weight: 1},
  {personA: 'WDJ', personB: 'YML', weight: 1},
  {personA: 'WDJ', personB: 'HEL', weight: 3},
  {personA: 'WDJ', personB: 'FEL', weight: 2},
  {personA: 'WDJ', personB: 'BHW', weight: 2},
  {personA: 'WDJ', personB: 'HAA', weight: 2},
  {personA: 'WDJ', personB: 'MA', weight: 1},
  {personA: 'YCH', personB: 'TEK', weight: 2},
  {personA: 'YCH', personB: 'BA', weight: 2},
  {personA: 'YCH', personB: 'CJE', weight: 1},
  {personA: 'YCH', personB: 'BHW', weight: 2},
  {personA: 'YCH', personB: 'HAA', weight: 2},
  {personA: 'YCH', personB: 'MMR', weight: 3},
  {personA: 'YCH', personB: 'WCV', weight: 1},
  {personA: 'YCH', personB: 'TKH', weight: 3},
  {personA: 'YCH', personB: 'TYS', weight: 1},
  {personA: 'TKH', personB: 'LDE', weight: 3},
  {personA: 'TKH', personB: 'YML', weight: 3},
  {personA: 'TKH', personB: 'FEL', weight: 3},
  {personA: 'TKH', personB: 'BHW', weight: 1},
  {personA: 'TKH', personB: 'HAA', weight: 1},
  {personA: 'TKH', personB: 'CLR', weight: 1},
  {personA: 'TKH', personB: 'WJH', weight: 3},
  {personA: 'TKH', personB: 'CCW', weight: 2},
  {personA: 'TKH', personB: 'TYS', weight: 3},
  {personA: 'YTP', personB: 'PZ', weight: 3},
  {personA: 'YTP', personB: 'BH', weight: 1},
  {personA: 'YTP', personB: 'LDE', weight: 2},
  {personA: 'YTP', personB: 'CJE', weight: 3},
  {personA: 'YTP', personB: 'BHW', weight: 2},
  {personA: 'YTP', personB: 'WCV', weight: 1},
  {personA: 'YTP', personB: 'MA', weight: 1},
  {personA: 'MKL', personB: 'PZ', weight: 3},
  {personA: 'MKL', personB: 'BH', weight: 2},
  {personA: 'MKL', personB: 'TEK', weight: 1},
  {personA: 'MKL', personB: 'CML', weight: 1},
  {personA: 'MKL', personB: 'LDE', weight: 1},
  {personA: 'MKL', personB: 'PMF', weight: 3},
  {personA: 'MKL', personB: 'LHW', weight: 1},
  {personA: 'RW', personB: 'PZ', weight: 3},
  {personA: 'RW', personB: 'TEK', weight: 1},
  {personA: 'RW', personB: 'HCY', weight: 1},
  {personA: 'RW', personB: 'CML', weight: 1},
  {personA: 'RW', personB: 'LDE', weight: 1},
  {personA: 'RW', personB: 'HEL', weight: 1},
  {personA: 'RW', personB: 'CLR', weight: 1},
  {personA: 'RW', personB: 'WCV', weight: 1},
  {personA: 'GR', personB: 'BA', weight: 3},
  {personA: 'GR', personB: 'CML', weight: 1},
  {personA: 'GR', personB: 'HEL', weight: 1},
  {personA: 'GR', personB: 'FEL', weight: 2},
  {personA: 'GR', personB: 'BHW', weight: 1},
  {personA: 'GR', personB: 'HAA', weight: 2},
  {personA: 'GR', personB: 'MMR', weight: 3},
  {personA: 'HL', personB: 'PZ', weight: 1},
  {personA: 'HL', personB: 'TEK', weight: 1},
  {personA: 'HL', personB: 'LDE', weight: 3},
  {personA: 'HL', personB: 'PMF', weight: 1},
  {personA: 'HL', personB: 'YML', weight: 3},
  {personA: 'HL', personB: 'MHT', weight: 3},
  {personA: 'HL', personB: 'LHW', weight: 1},
  {personA: 'CCW', personB: 'TEK', weight: 1},
  {personA: 'CCW', personB: 'HCY', weight: 2},
  {personA: 'CCW', personB: 'CML', weight: 2},
  {personA: 'CCW', personB: 'CCY', weight: 1},
  {personA: 'CCW', personB: 'YML', weight: 2},
  {personA: 'CCW', personB: 'HEL', weight: 1},
  {personA: 'CCW', personB: 'FEL', weight: 2},
  {personA: 'CCW', personB: 'CLR', weight: 2},
  {personA: 'CCW', personB: 'MHT', weight: 1},
  {personA: 'TYS', personB: 'PZ', weight: 1},
  {personA: 'TYS', personB: 'TEK', weight: 2},
  {personA: 'TYS', personB: 'LDE', weight: 3},
  {personA: 'TYS', personB: 'YML', weight: 2},
  {personA: 'TYS', personB: 'HEL', weight: 2},
  {personA: 'TYS', personB: 'BHW', weight: 1},
  {personA: 'TYS', personB: 'WJH', weight: 3},
  {personA: 'TYS', personB: 'MHT', weight: 3},
  {personA: 'TYS', personB: 'LHW', weight: 1},
  {personA: 'MA', personB: 'TEK', weight: 2},
  {personA: 'MA', personB: 'CML', weight: 1},
  {personA: 'MA', personB: 'CJE', weight: 1},
  {personA: 'MA', personB: 'HEL', weight: 1},
  {personA: 'MA', personB: 'FEL', weight: 2},
  {personA: 'MA', personB: 'BHW', weight: 3},
  {personA: 'MA', personB: 'HAA', weight: 1},
  {personA: 'MA', personB: 'MMR', weight: 3},
  {personA: 'MA', personB: 'WCV', weight: 1},

  {personA: 'PZ', personB: 'BH', weight: 3},
  {personA: 'PZ', personB: 'AVB', weight: 1},
  {personA: 'PZ', personB: 'CLR', weight: 1},
  {personA: 'PZ', personB: 'HCY', weight: 2},
  {personA: 'PZ', personB: 'LDE', weight: 2},
  {personA: 'BH', personB: 'AVB', weight: 1},
  {personA: 'BH', personB: 'CLR', weight: 1},
  {personA: 'TEK', personB: 'HEL', weight: 1},
  {personA: 'TEK', personB: 'FEL', weight: 1},
  {personA: 'TEK', personB: 'MMR', weight: 2},
  {personA: 'BA', personB: 'HAA', weight: 1},
  {personA: 'HCY', personB: 'CML', weight: 2},
  {personA: 'HCY', personB: 'LDE', weight: 1},
  {personA: 'HCY', personB: 'YML', weight: 1},
  {personA: 'HCY', personB: 'WEC', weight: 1},
  {personA: 'CML', personB: 'LDE', weight: 1},
  {personA: 'CML', personB: 'YML', weight: 1},
  {personA: 'CML', personB: 'BHW', weight: 1},
  {personA: 'LDE', personB: 'CCY', weight: 3},
  {personA: 'LDE', personB: 'PMF', weight: 2},
  {personA: 'LDE', personB: 'YML', weight: 3},
  {personA: 'CJE', personB: 'CCY', weight: 3},
  {personA: 'PMF', personB: 'MHT', weight: 2},
  {personA: 'HEL', personB: 'FEL', weight: 3},
  {personA: 'BHW', personB: 'HAA', weight: 1},
  {personA: 'WJH', personB: 'WCV', weight: 1},

  {personA: 'MR', personB: 'SJJ', weight: 3},
  {personA: 'MR', personB: 'GR', weight: 1},
  {personA: 'MCJ', personB: 'SCS', weight: 3},
  {personA: 'MCJ', personB: 'CAS', weight: 1},
  {personA: 'MCJ', personB: 'HAD', weight: 1},
  {personA: 'SHB', personB: 'FC', weight: 3},
  {personA: 'SHB', personB: 'HDA', weight: 3},
  {personA: 'SHB', personB: 'WDJ', weight: 2},
  {personA: 'SHB', personB: 'SJJ', weight: 1},
  {personA: 'SHB', personB: 'HAD', weight: 1},
  {personA: 'LDM', personB: 'YPF', weight: 3},
  {personA: 'LDM', personB: 'SJJ', weight: 2},
  {personA: 'LDM', personB: 'FC', weight: 1},
  {personA: 'KJL', personB: 'YPF', weight: 3},
  {personA: 'KJL', personB: 'FC', weight: 1},

  // {personA: 'SJJ', personB: 'DSS', weight: 1},
  // {personA: 'LFC', personB: 'DSS', weight: 2},
  // {personA: 'NPC', personB: 'DSS', weight: 3},
  // {personA: 'YPF', personB: 'DSS', weight: 2},
  // {personA: 'LKW', personB: 'DSS', weight: 1},
  // {personA: 'FC', personB: 'DSS', weight: 1},
  // {personA: 'CAS', personB: 'DSS', weight: 1},
  // {personA: 'WDJ', personB: 'DSS', weight: 1},
  // {personA: 'YCH', personB: 'DSS', weight: 2},
  // {personA: 'MKL', personB: 'DSS', weight: 3},
  // {personA: 'RW', personB: 'DSS', weight: 1},
  // {personA: 'GR', personB: 'DSS', weight: 2},
  // {personA: 'CCW', personB: 'DSS', weight: 2},
  // {personA: 'MA', personB: 'DSS', weight: 3},
  // {personA: 'DSS', personB: 'CML', weight: 1},
  // {personA: 'DSS', personB: 'BHW', weight: 1},
  // {personA: 'DSS', personB: 'BV', weight: 1},
  // {personA: 'DSS', personB: 'MMR', weight: 1},
  // {personA: 'DSS', personB: 'CCY', weight: 2},
  // {personA: 'SJJ', personB: 'BV', weight: 3},
  // {personA: 'YPF', personB: 'BV', weight: 1},
  // {personA: 'SWY', personB: 'BV', weight: 1},
  // {personA: 'YCH', personB: 'BV', weight: 1},
  // {personA: 'TKH', personB: 'BV', weight: 1},
  // {personA: 'GR', personB: 'BV', weight: 1},
  // {personA: 'TEK', personB: 'BV', weight: 1},
  // {personA: 'BV', personB: 'MMR', weight: 2},
]
