export interface DesignSection {
  section: string
  subsections: string[]
}

const SEPARATOR_LINE = '=============================';

export const DESIGN_SECTIONS: DesignSection[] = [
  {
    section: 'Customer',
    subsections: [
      'Meeting / Summary',
      'Meeting / Timeline',
      'Meeting / Countdown',
      'Meeting / Starter Grid',
      'Meeting / JKC & TNC',
      'Meeting / Pool',
      'Meeting / Dividend',
      SEPARATOR_LINE,
      'Racecard / Recommendation',
      'Racecard / Starter Card',
      SEPARATOR_LINE,
      'Odds / QQP, FCT & DBL Grid',
      'Odds / Range Control',
      'Odds / Combination Selection',
      'Odds / Betline Command Copy',
      'Odds / Dutching Return Estimation',
      SEPARATOR_LINE,
      'Trend / Full Detailed View',
      'Trend / Top Earning Players',
      'Trend / Detailed Earning View',
      'Trend / Collaboration',
      'Trend / Signal',
      'Trend / Pool & Dividend History',
      'Trend / Recommendation History',
      'Trend / Trackwork History',
      'Trend / Draw Inheritance',
      SEPARATOR_LINE,
      'Form / Report',
      'Form / Scratched & Prompted',
      'Form / Birthday & Milestone',
      'Form / Bet Upload & Analytics',
      'Form / Fixture',
      SEPARATOR_LINE,
      '* Game / Intro',
      '* Game / Entry',
      '* Game / Gameplay',
      SEPARATOR_LINE,
      '* Pricing / Subscription',
      '* Pricing / Gold',
      '* Pricing / Payment',
      '* Pricing / Redemption',
      '* Pricing / Order History',
      '* Pricing / New User',
      SEPARATOR_LINE,
      '* Account / Login',
      '* Account / Registration',
      '* Account / Management',
      SEPARATOR_LINE,
      '* Seminar / Intro',
      '* Seminar / Registration',
      '* Seminar / Payment',
      SEPARATOR_LINE,
      '* Feedback / Collection',
      '* Feedback / History',
      SEPARATOR_LINE,
      '* Announcement / Display',
    ]
  },
  {
    section: 'Administrator',
    subsections: [
      'Form / Interview',
      'Form / Player',
      'Form / Owner',
      'Form / Connection',
      SEPARATOR_LINE,
      'Backtest / General',
      'Backtest / Exact',
      SEPARATOR_LINE,
      '* Pricing / Price Tag',
      '* Pricing / Order & Sales',
      '* Pricing / Refund Management',
      '* Pricing / Redemption Creation',
      '* Pricing / User Account Crediting',
      SEPARATOR_LINE,
      '* Seminar / Session Creation',
      '* Seminar / Registration Status',
      SEPARATOR_LINE,
      '* Misc / Feedback Management',
      '* Misc / Announcement Management',
      '* Misc / System Health Check',
      '* Misc / User Report',
      '* Misc / Auditing',
    ]
  },
]
